# Generated by Django 5.0.2 on 2024-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezy_users',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ezy_users',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
