# Generated by Django 5.0.1 on 2024-03-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_ezy_users_age_alter_ezy_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezy_users',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ezy_users',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
