# Generated by Django 5.0.2 on 2024-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ezysurveyquestions_ezyresponses_ezysurveys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ezysurveyquestions',
            name='q_options',
        ),
        migrations.AlterField(
            model_name='ezysurveys',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
