# Generated by Django 5.0.2 on 2024-04-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ezysurveyquestions_q_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ezyresponses',
            name='response_option',
        ),
    ]
