# Generated by Django 5.0.1 on 2024-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_forms',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100)),
                ('form_desc', models.CharField(max_length=1000)),
                ('form_created', models.DateTimeField(verbose_name='date created')),
                ('form_updated', models.DateTimeField(verbose_name='date updated')),
                ('form_status', models.BooleanField(default=True)),
                ('form_owner', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_forms',
            },
        ),
    ]
