# Generated by Django 5.0.1 on 2024-03-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_ezy_users_age_alter_ezy_users_phone'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
                ('question_type', models.CharField(max_length=100)),
                ('question_options', models.CharField(max_length=1000)),
                ('question_required', models.BooleanField(default=False)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user_forms')),
            ],
            options={
                'db_table': 'form_questions',
            },
        ),
        migrations.CreateModel(
            name='form_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user_forms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.ezy_users')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.form_questions')),
            ],
            options={
                'db_table': 'form_answers',
            },
        ),
    ]
