# Generated by Django 5.0.1 on 2024-03-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_remove_form_questions_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='grievances',
            fields=[
                ('grievance_id', models.AutoField(primary_key=True, serialize=False)),
                ('grievance_user', models.CharField(max_length=100)),
                ('grievance_issue', models.CharField(max_length=100)),
                ('grievance_message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'grievances',
            },
        ),
    ]
